<?php


namespace App\Repositories;


use App\Models\Comment;
use App\Repositories\Interfaces\CommentRepositoryInterface;

class CommentRepository extends CoreRepository implements CommentRepositoryInterface
{
    public function getModel()
    {
        return Comment::class;
    }

    public function start()
    {
        return parent::start(); // TODO: Change the autogenerated stub
    }

    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
    public function getById($id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }

    public function storePost($request, $type){
        $req = $this->start()->create([
            'user_id' => $request->user_id,
            'body' => $request->body,
            'commentable_id' => $request->post_id,
            'commentable_type' => $type,
        ]);
        if($request->parent_id){
            $req->update([
                'parent_id' => $request->parent_id
            ]);
        }
    }
}
