<?php


namespace App\Repositories;


use App\Models\Comment;
use App\Repositories\Interfaces\CommentRepositoryInterface;

class CommentRepository extends CoreRepository implements CommentRepositoryInterface
{
    public function getModel()
    {
        return Comment::class;
    }

    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
    public function getById($id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }
}
