<?php


namespace App\Repositories;


use App\Models\Tag;
use App\Repositories\Interfaces\TagRepositoryInterface;

class TagRepository extends CoreRepository implements TagRepositoryInterface
{
    public function getModel()
    {
        return Tag::class;
    }

    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
}
